/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-oct.-2023 18:30:06 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Categoria` CASCADE
;

DROP TABLE IF EXISTS `Detalleventa` CASCADE
;

DROP TABLE IF EXISTS `Inventario` CASCADE
;

DROP TABLE IF EXISTS `Notaventa` CASCADE
;

DROP TABLE IF EXISTS `Producto` CASCADE
;

DROP TABLE IF EXISTS `Usuario` CASCADE
;

/* Create Tables */

CREATE TABLE `Categoria`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Nombre` VARCHAR(50) NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);

CREATE TABLE `Detalleventa`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Cantidad` INT NULL,
    `idNotaventa` INT NULL,
    `idProducto` INT NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);

CREATE TABLE `Inventario`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Accion` VARCHAR(50) NULL,
    `Cantidad` INT NULL,
    `idUsuario` BIGINT UNSIGNED NOT NULL,
    `idProducto` INT NOT NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);

CREATE TABLE `Notaventa`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Fecha` DATE NULL,
    `Montototal` DOUBLE(10,2) NULL,
    `idUsuario` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);

CREATE TABLE `Producto`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Nombre` VARCHAR(50) NULL,
    `Precio` DOUBLE(10,2) NULL,
    `Stock` INT NULL,
    `Url` TEXT NULL,		
    `idCategoria` INT NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);

/*CREATE TABLE `Usuario`
(
    `id` INT NOT NULL AUTO_INCREMENT, -- Cambiado a autoincrementable
    `Correo` VARCHAR(50) NULL,
    `Nombre` VARCHAR(50) NULL,
    `Password` VARCHAR(50) NULL,
    `Rol` INT NULL,
    PRIMARY KEY (`id`) -- Definido como clave primaria
);*/

/* Create Foreign Key Constraints */

ALTER TABLE `Detalleventa` 
ADD CONSTRAINT `FK_DetalleVenta_Producto`
FOREIGN KEY (`idProducto`) REFERENCES `Producto` (`id`) 
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Detalleventa` 
 ADD CONSTRAINT `FK_DetalleVenta_NotaVenta`
	FOREIGN KEY (`idNotaventa`) REFERENCES `Notaventa` (`id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Inventario` 
 ADD CONSTRAINT `FK_Inventario_Producto`
	FOREIGN KEY (`idProducto`) REFERENCES `Producto` (`id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Inventario` 
 ADD CONSTRAINT `FK_Inventario_users`
	FOREIGN KEY (`idUsuario`) REFERENCES `users` (`id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Notaventa` 
 ADD CONSTRAINT `FK_Notaventa_users`
	FOREIGN KEY (`idUsuario`) REFERENCES `users` (`id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Producto` 
 ADD CONSTRAINT `FK_Producto_Categoria`
	FOREIGN KEY (`idCategoria`) REFERENCES `Categoria` (`id`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;

INSERT INTO categoria (Nombre) VALUES
	 ('Ron'),
	 ('Singani'),
	 ('Vino'),
	 ('Whisky');

INSERT INTO producto (Nombre,Precio,Stock,Url,idCategoria) VALUES
	 ('Havana Club - 7 Años - Ron  - 700cc',126.0,28,'../assets/ron.avif',1),
	 ('Havana Club - Reserva - Ron - Cuba - 1000cc',95.0,45,'../assets/ron2.avif',1),
	 ('Casa Real - Etiqueta Roja 750cc',50.0,60,'../assets/singani.avif',2),
	 ('Casa Real - Etiqueta Negra 750cc',75.0,70,'../assets/singani2.avif',2),
	 ('Campos de Solana - Trivarietal 750cc',100.0,30,'../assets/vino.webp',3),
	 ('Errazuriz - Max Reserva 750cc',162.0,35,'../assets/vino2.avif',3),
	 ('Johnnie Walker - White Walker  - 750cc',310.0,50,'../assets/whisky.webp',4),	 
	 ('Chivas Regal - 12 Años - 1000cc',299.0,70,'../assets/whisky2.avif',4);
